steps:
- script: 'npm install'
  displayName: 'Install Dependencies'

- script: |
   npm run build
   
  displayName: 'Build the project'


- task: ArchiveFiles@2
  displayName: 'Archive $(Build.ArtifactStagingDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: static-next-web'
  inputs:
    ArtifactName: 'static-next-web'